#ifndef __ELECTRIA_ACTION_H

enum {
	ACTION_NO_ACTION = -1,
	ACTION_ARM_UP = 1,
	ACTION_ROTATION_CCW,
	ACTION_ROTATION_CW,
	ACTION_ARM_DOWN,
	ACTION_SWIPE_RIGHT,
	ACTION_SWIPE_LEFT,
};

#define __ELECTRIA_ACTION_H
#endif
